### ISSUE TITLE
wstool Cannot Download Some Packages

### ISSUE THREAD

**Issue by EpicWolverine** [ros-gbp/ros_comm-release#4] opened 2019-02-13 05:03 UTC
I'm trying to build ROS from source following [this tutorial](http://wiki.ros.org/melodic/Installation/Source) since there are no prebuilt packages for Debian on armhf. I need to use Debian over Ubuntu for external reasons.

While trying to use wstool to fetch the packages in `melodic-desktop.rosinstall`, three critical packages could not be downloaded. These are `ros_comm/ros_comm`, `ros_comm/rosbag_storage`, and `ros_comm/rosgraph`. 

I get the following errors while `wstool update -t src` is scanning:
```
[ros_comm/ros_comm] Fetching https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/ros_comm/1.14.3-0.tar.gz (version ros_comm-release-release-melodic-ros_comm-1.14.3-0) to /home/debian/catkin_ws/src/ros_comm/ros_comm
ERROR [vcstools] Tarball download unpack failed: u"ros_comm-release-release-melodic-ros_comm-1.14.3-0 is not a subdirectory with contents in members [u'ros_comm-release-release-melodic-ros_comm']"[/vcstools]
[ros_comm/rosbag_storage] Fetching https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosbag_storage/1.14.3-0.tar.gz (version ros_comm-release-release-melodic-rosbag_storage-1.14.3-0) to /home/debian/catkin_ws/src/ros_comm/rosbag_storage
ERROR [vcstools] Tarball download unpack failed: u"ros_comm-release-release-melodic-rosbag_storage-1.14.3-0 is not a subdirectory with contents in members [u'ros_comm-release-release-melodic-rosbag_storage']"[/vcstools]
[ros_comm/rosgraph] Fetching https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosgraph/1.14.3-0.tar.gz (version ros_comm-release-release-melodic-rosgraph-1.14.3-0) to /home/debian/catkin_ws/src/ros_comm/rosgraph
ERROR [vcstools] Tarball download unpack failed: u"ros_comm-release-release-melodic-rosgraph-1.14.3-0 is not a subdirectory with contents in members [u'ros_comm-release-release-melodic-rosgraph']"[/vcstools]
```
and I get the following errors at the end of execution:
```
Exception caught during install: Error processing 'ros_comm/ros_comm' : [ros_comm/ros_comm] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/ros_comm/1.14.3-0.tar.gz version ros_comm-release-release-melodic-ros_comm-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/ros_comm failed.
Error processing 'ros_comm/rosbag_storage' : [ros_comm/rosbag_storage] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosbag_storage/1.14.3-0.tar.gz version ros_comm-release-release-melodic-rosbag_storage-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/rosbag_storage failed.
Error processing 'ros_comm/rosgraph' : [ros_comm/rosgraph] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosgraph/1.14.3-0.tar.gz version ros_comm-release-release-melodic-rosgraph-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/rosgraph failed.

ERROR in config: Error processing 'ros_comm/ros_comm' : [ros_comm/ros_comm] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/ros_comm/1.14.3-0.tar.gz version ros_comm-release-release-melodic-ros_comm-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/ros_comm failed.
Error processing 'ros_comm/rosbag_storage' : [ros_comm/rosbag_storage] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosbag_storage/1.14.3-0.tar.gz version ros_comm-release-release-melodic-rosbag_storage-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/rosbag_storage failed.
Error processing 'ros_comm/rosgraph' : [ros_comm/rosgraph] Checkout of https://github.com/ros-gbp/ros_comm-release/archive/release/melodic/rosgraph/1.14.3-0.tar.gz version ros_comm-release-release-melodic-rosgraph-1.14.3-0 into /home/debian/catkin_ws/src/ros_comm/rosgraph failed.
```

After further investigation, it seems may be some strange stuff happening on GitHub's end. On another computer, going to the listed URLs in the errors downloads the tar in my browser but going to the associated release tag page gives me a 404. Digging through the [list of releases](https://github.com/ros-gbp/ros_comm-release/releases?after=release%2Fmelodic%2Frosmaster%2F1.14.3-0), similar packages load fine ([`roslaunch`](https://github.com/ros-gbp/ros_comm-release/releases/tag/release%2Fmelodic%2Froslaunch%2F1.14.3-0)) but all three packages I'm having issues with do not ([`ros_comm`](https://github.com/ros-gbp/ros_comm-release/releases/tag/release%2Fmelodic%2Fros_comm%2F1.14.3-0)).

Since I can download the packages manually, but wstool can't download them and I can't figure out how to trick wstool into using the manually downloaded tars, I'm not sure how to proceed. Any help would be appreciated.

If this is the wrong place to report this, please direct me to the correct place.

**Comment by dirk-thomas** [comment] 2019-02-13 16:24
Duplicate of ros/ros_comm#1598.

**Closed as completed by dirk-thomas** 2019-02-13 16:24 UTC
Labels: duplicate

**Comment by EpicWolverine** [comment] 2019-02-13 16:50
Looks like I just tried this at the wrong time then. Glad to see a fix is already in the works. Thanks for your help.
